### PR TITLE
Pull request with type [CREATE] for user [JordanTheITGuy] and object type [ConfigurationItem] - titled [LOG4J - Hash Level Evaluation]

### PR DESCRIPTION
**Pull request by JordanTheITGuy**
Automated pull request from the Endpoint Configuration Manager Community hub.

### CODE REVIEW

**Comment by AdamGrossTX** [comment]
and this one too @silveyy

**Comment by silveyy** [comment]
@AdamGrossTX  Done but we need one more reviewer (hint, hint).

---
In reply to: [995313088](https://github.com/microsoft/configmgr-hub/pull/177#issuecomment-995313088) [](http://example.com/codeflow?ancestors=995313088,995313088)

**Review by silveyy — APPROVED** [review]
:shipit:

**Review by AdamGrossTX — APPROVED** [review]
Looks good.

**Pull request merged**
