### PR TITLE
Pull request with type [UPDATE] for user [philjorgensen] and object type [Script] - titled [Odometer]

### PR DESCRIPTION
**Pull request by philjorgensen**
Automated pull request from the Endpoint Configuration Manager Community hub.

### CODE REVIEW

**Review by kmyrup — DISMISSED** [review]

**Review by Ioan-Popovici — COMMENTED** [review]
I don't see any changes here beside a line being deleted, do you wanted to do other changes and published this by mistake?

**Comment by philjorgensen** [comment]
> I don't see any changes here beside a line being deleted, do you wanted to do other changes and published this by mistake?

In case you missed my comment in Pull #83, I wanted to see if there's a way to rename the Script without having to re-submit.  If that's not possible, how can I remove the original from the hub?  I appreciate your help Ioan.

**Comment by Ioan-Popovici** [comment]
> > I don't see any changes here beside a line being deleted, do you wanted to do other changes and published this by mistake?
> 
> 
> 
> In case you missed my comment in Pull #83, I wanted to see if there's a way to rename the Script without having to re-submit.  If that's not possible, how can I remove the original from the hub?  I appreciate your help Ioan.

I'm not sure if you can do that. I don't what the backend is but with git there's no easy way of doing that according to my limited understanding of GIT

**Comment by philjorgensen** [comment]
> > > I don't see any changes here beside a line being deleted, do you wanted to do other changes and published this by mistake?
> > 
> > 
> > In case you missed my comment in Pull #83, I wanted to see if there's a way to rename the Script without having to re-submit.  If that's not possible, how can I remove the original from the hub?  I appreciate your help Ioan.
> 
> About removing a pull request.
> I'm not sure if you can do that. I don't what the backend is but with git there's no easy way of doing that according to my limited understanding of GIT
> 
> What you can do is load your committed branch, edit your original script and publish a new commit. I don't know if that will change the name in Community Hub though.
> 
> I would also like to know if it's possible to remove a submission.

Ioan, I _think_ I did the rename right.  I'm still learning Git as well!

**Comment by Ioan-Popovici** [comment]
Approved, also have a look at variable and parameter naming conventions. The rest seems fine.

**Review by Ioan-Popovici — APPROVED** [review]
This should be merged.

**Pull request merged**
