### PR TITLE
Pull request with type [CREATE] for user [philjorgensen] and object type [Script] - titled [Odometer]

### PR DESCRIPTION
**Pull request by philjorgensen**
Automated pull request from the Endpoint Configuration Manager Community hub.

### CODE REVIEW

**Review by kmyrup — APPROVED** [review]

**Review by Ioan-Popovici — APPROVED** [review]
For future reference I suggest you have a look at the PowerShell naming [guidelines](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/strongly-encouraged-development-guidelines).

This being said, although I think a HWI extension would be more suitable for this purpose, this code works as intended and is easy readable.

This should be merged.

**Comment by philjorgensen** [comment]
Ioan, I wanted to add to the description a [link](https://github.com/CDRT/Library/blob/master/mof/odometer.mof) to the extension for this to work.

**Comment by kmyrup** [comment]
> Ioan, I wanted to add to the description a [link](https://github.com/CDRT/Library/blob/master/mof/odometer.mof) to the extension for this to work.

You can go back to this item in the Community hub in your admin console, and push an update to the script, during which you can specify the link into your description (watch out for our current limitation of 255 characters in the description though).

If the "Push Update" button is not present for you, then you may need to make a cosmetic change to the script in your hierarchy (and get it approved) so that the hub will detect you have pending changes to push up.

image

**Comment by philjorgensen** [comment]
Thank you, that did the trick!

Regards,
Phil Jorgensen   |  Commercial Deployment Readiness Team   |   8001 Development Dr, B8-2NL2, Durham, NC 27709

From: KevinM_MSFT ***@***.***>
Sent: Tuesday, March 16, 2021 6:11 PM
To: microsoft/configmgr-hub ***@***.***>
Cc: Phil Jorgensen ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/configmgr-hub] Pull request with type [CREATE] for user [philjorgensen] and object type [Script] - titled [Odometer] (#83)


Ioan, I wanted to add to the description a link<https://github.com/CDRT/Library/blob/master/mof/odometer.mof> to the extension for this to work.

You can go back to this item in the Community hub in your admin console, and push an update to the script, during which you can specify the link into your description (watch out for our current limitation of 255 characters in the description though).

If the "Push Update" button is not present for you, then you may need to make a cosmetic change to the script in your hierarchy (and get it approved) so that the hub will detect you have pending changes to push up.

[Image removed by sender. image]<https://user-images.githubusercontent.com/38894175/111386664-cf261680-8669-11eb-80ca-b0d3cc1532e1.png>

**Comment by philjorgensen** [comment]
> You can go back to this item in the Community hub in your admin console, and push an update to the script, during which you can specify the link into your description (watch out for our current limitation of 255 characters in the description though).
> 
> If the "Push Update" button is not present for you, then you may need to make a cosmetic change to the script in your hierarchy (and get it approved) so that the hub will detect you have pending changes to push up.
> 
> image

Thank you, that worked!  Is there a way to change the item name as Ioan pointed out or will I have to make another submission?  If the latter, can the original be removed?

**Pull request merged**
