### PR TITLE
Pull request with type [CREATE] for user [PanuSaukko] and object type [CMPivotQuery] - titled [Teams versions]

### PR DESCRIPTION
**Pull request by PanuSaukko**
Automated pull request from the Endpoint Configuration Manager Community hub.

### CODE REVIEW

**Review by kmyrup — APPROVED** [review]

**Review by silveyy — APPROVED** [review]

**Review by Ioan-Popovici — CHANGES_REQUESTED** [review]
Hardcoded paths are never a good idea.
You could use '%WinDir%' or '%SystemRoot%'.

**Comment by silveyy** [comment]
> Hardcoded paths are never a good idea.
> You could use '%WinDir%' or '%SystemRoot%'.

Agree, but wasn't sure if we supported var's in CMPivot :|. If we do then %SystemDrive% is probably a good candidate here instead of C:

**Comment by Ioan-Popovici** [comment]
The env variables are supported :)

**Comment by Ioan-Popovici** [comment]
> > Hardcoded paths are never a good idea.
> 
> > You could use '%WinDir%' or '%SystemRoot%'.
> 
> 
> 
> Agree, but wasn't sure if we supported var's in CMPivot :|. If we do then %SystemDrive% is probably a good candidate here instead of C: 

The env variables are supported:)

**Comment by PanuSaukko** [comment]
> > > Hardcoded paths are never a good idea.
> > 
> > 
> > > You could use '%WinDir%' or '%SystemRoot%'.
> > 
> > 
> > Agree, but wasn't sure if we supported var's in CMPivot :|. If we do then %SystemDrive% is probably a good candidate here instead of C:
> 
> The env variables are supported:)

%Windir% works with CMPivot, but I cannot use %SystemRoot% in CMPivot for some reason. :-)

And %Windir% refers to c:\windows, so cannot use that.

Panu

**Comment by PanuSaukko** [comment]
> > > Hardcoded paths are never a good idea.
> > 
> > 
> > > You could use '%WinDir%' or '%SystemRoot%'.
> > 
> > 
> > Agree, but wasn't sure if we supported var's in CMPivot :|. If we do then %SystemDrive% is probably a good candidate here instead of C:
> 
> The env variables are supported:)

I modified the query to use %SystemDrive%. Had to create a new Pull request, because I don't know how to edit an existing request.

**Comment by Ioan-Popovici** [comment]
You can sync this one and update it but a new one works too. You can close this one.

**Comment by Ioan-Popovici** [comment]
Merged the second request this PR can be closed

**Comment by kmyrup** [comment]
Closing at the request of @PanuSaukko

**Pull request closed without merging**
