### PR TITLE
Pull request with type [CREATE] for user [AdamGrossTX] and object type [Script] - titled [Trigger Client Baseline Evaluation]

### PR DESCRIPTION
**Pull request by AdamGrossTX**
Automated pull request from the Configuration Manager community hub.

### CODE REVIEW

**Comment by AdamGrossTX** [comment]
I realized I messed up the description text for this one. How do you edit the PR to fix that?

**Comment by silveyy** [comment]
> I realized I messed up the description text for this one. How do you edit the PR to fix that?
Not supported in this months release (should be there next month). For now if you want to give the updated description we can update for you.

**Comment by AdamGrossTX** [comment]
New description should read:

Trigger a the evaluation of client baselines where PolicyType is Null

Thanks!

Adam Gross
@AdamGrossTX<https://twitter.com/AdamGrossTX>
https://ASquareDozen.com<http://www.asquaredozen.com/>
https://SysManSquad.com
https://Intune.Training<https://intune.training>
https://CodingWithCaroline.com
Microsoft MVP | Enterprise Mobility<https://mvp.microsoft.com/en-us/PublicProfile/5003519?fullName=Adam%20Gross>

[cid:0ea2e523-00dd-4d7b-95d9-b3752693a5be]



________________________________

**Comment by AdamGrossTX** [comment]
Lol. Yes Please. 🙂

Adam Gross
@AdamGrossTX<https://twitter.com/AdamGrossTX>
https://ASquareDozen.com<http://www.asquaredozen.com/>
https://SysManSquad.com
https://Intune.Training<https://intune.training>
https://CodingWithCaroline.com
Microsoft MVP | Enterprise Mobility<https://mvp.microsoft.com/en-us/PublicProfile/5003519?fullName=Adam%20Gross>

[cid:c67e8862-b285-4bdb-950f-c55f9c6ef2af]



________________________________

**Review by kmyrup — APPROVED** [review]
Approved and updated the description in metadata as well.

**Pull request merged**
